### ISSUE TITLE
Potential rounding error of "swresample"

### ISSUE THREAD

**Issue by MasterInQuestion** [librempeg/librempeg#11]
https://trac.ffmpeg.org/ticket/11138

**Comment by richardpl** [comment]
Sorry.

**Comment by MasterInQuestion** [comment]
No matter.

**Comment by richardpl** [comment]
See new aquant filter, it can use any kind of noise-shaping (curves) via external filters. In my very limited testing it appears to work fine.

**Comment by MasterInQuestion** [comment]
Thanks for the hint.
    But many aspects about the original issue remain unclear:
    That make it wondrous about whether such should be considered a real issue.

    "aquant" related:
    https://github.com/librempeg/librempeg/blob/master/libavfilter/af_aquant.c
    https://github.com/librempeg/librempeg/blob/master/libavfilter/aquant_template.c
    https://github.com/search?type=code&q=repo:librempeg/librempeg+%22aquant%22
    [ https://github.com/librempeg/librempeg/commit/b887bfa653425020af25630b3821f491d2324187](https://github.com/librempeg/librempeg/commit/b887bfa653425020af25630b3821f491d2324187)

**Comment by richardpl** [comment]
The added dither (noise) data should not have DC bias (positive or negative) at all.
floor() will round differently negative and positive values so round() is better to use (but that is just for aquant filter that use noise-shaped processed output).

But floor() -> round() issue can not fix added dither noise bias (eg. DC offset of dither noise itself is not 0.0000% - there is already DC offset bias in added noise itself so rounding can not improve such situation).

I'm not interested in fixing swresample library code at all, that's why here are multiple filters doing swresample functionality:

asf2sf - conversion between different audio sample formats (supports threading)
ardftsrc - audio sample rate conversion (supports threading, still looking at improving quality and performance)
channelmix - dynamic adaptive audio channel mixing (like pan filter but with non-fixed pan coefficients)
aquant - audio samples quantization with noise-shaping (might add dithering too but later.., its less important for me)

**Comment by MasterInQuestion** [comment]
There are several other things related with the issue involved.
    Which I must first resolve, to be able to provide reasonable comment on this thread.
    Pardon the delay.

**Comment by ValeZAA** [comment]
You know this is a real bug... fix it

**Comment by richardpl** [comment]
Sure,
libswresample library is scheduled for removal from project codebase.
All users should switch to libavfilter directly.

**Comment by MasterInQuestion** [comment]
Alike DC bias is generally subliminal. (unnoticeable on typical data)
    While the accurate rounding practice may noticeably degrade compressibility...

**Comment by richardpl** [comment]
you should not use swresample (without soxr) for any serious work, its barely useful for casual listening.
